from typing import List, Optional

class GitCommandError(Exception): ...
class NoSuchPathError(Exception): ...


class Remote:
    def pull(self) -> List[str]: ...


class Repo:
    def __init__(self, path: Optional[str] = None): ...

    @staticmethod
    def clone_from(url: str, to_path: str) -> None: ...

    def remote(self) -> Remote: ...
